// Generated by CoffeeScript 1.3.1
(function() {
  var tea_test;

  tea_test = new Tea;

  console.log(window.Tea)

  describe("tea", function() {
    it("should exist", function() {
      expect(tea_test).not.to.be(void 0);
    });
    it("should have default name of Earl Gray", function() {
      expect(tea_test.get("name")).to.eql("Earl Gray");
    });
  });

  describe("something", function() {
    it("should get substring", function() {
      expect("something".substr(4)).to.eql("thing");
    });
  });

  describe("addition", function() {
    it("should work naturally", function() {
      expect(1 + 1).to.eql(2);
    });
  });

  describe("lastly", function() {
    it("should not be empty", function() {
      expect({}).not.to.be(void 0);
    });
  });

  describe("what", function() {
    it("should not be undefined", function() {
      expect([]).not.to.be(void 0);
    });
  });

  describe("adding", function() {
    it("should add", function() {
      expect(2 + 2).to.eql(5);
    });
  });

}).call(this);
